config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  resources :listings, only: [:index, :show]
  resources :reservations do
    member do
      post '/cancel' => 'reservations#cancel'
    end
  end
  post 'webhooks/:source' => 'webhooks#create'

  namespace :host do
    resources :merchant_settings do
      collection do
        get '/connect' => 'merchant_settings#connect'
        get '/connected' => 'merchant_settings#connected'
      end
    end
    resources :listings do 
      resources :photos, only: [ :index, :new, :create, :destroy ]
      resources :rooms, only: [:index, :create, :destroy]
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id                :integer          not null, primary key
#  host_id           :integer          not null
#  title             :string           not null
#  about             :text
#  max_guests        :integer          default("1")
#  address_line1     :string
#  address_line2     :string
#  city              :string
#  state             :string
#  postal_code       :string
#  country           :string
#  lat               :decimal(10, 6)
#  lng               :decimal(10, 6)
#  status            :integer          default("0")
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  nightly_price     :integer
#  cleaning_fee      :integer
#  stripe_product_id :string
#
# Indexes
#
#  index_listings_on_host_id  (host_id)
#

class Listing < ApplicationRecord
  validates :title, presence: true
  validates :max_guests, numericality: { greater_than: 0, less_than_or_equel_to: 100 }
  validates :nightly_price, numericality: { greater_than: 0 }
  validates :cleaning_fee, numericality: { greater_than: 0 }
  belongs_to :host, class_name: 'User'
  has_many :rooms
  has_many :photos

  enum status: { draft: 0, published: 1, archived: 2 }

  scope :published, -> { where(status: :published )}


  after_commit :maybe_create_stripe_product, on: [:create, :update]

  def maybe_create_stripe_product
    return if !stripe_product_id.blank?

    product = Stripe::Product.create(
      name: title,
      url: Rails.application.routes.url_helpers.url_for(self),
      metadata: {
        clearbnb_id: id,
      }
    )
    self.update(stripe_product_id: product.id)
  end



end

app/controllers/host/listings_controller.rb
class Host::ListingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @listings = current_user.listings.all
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_create_params)
    if @listing.save
      redirect_to host_listing_path(@listing)
    else
      flash.now[:errors] = @listing.errors.full_messages
      render :new
    end
  end

  def show
    @listing = current_user.listings.find(params[:id])
  end

  def edit
    @listing = current_user.listings.find(params[:id])
  end

  def update
    @listing = current_user.listings.find(params[:id])
    if @listing.update(listing_update_params)
      redirect_to host_listing_path(@listing)
    else
      flash.now[:errors] = @listing.errors.full_messages
      render :edit
    end
  end


  def destroy
    @listing = current_user.listings.find(params[:id])
    @listing.update(status: :archived)
    redirect_to host_listing_path
  end

  private

  def listing_create_params
    params.require(:listing).permit(
      :title,
      :about,
      :max_guests,
      :address_line1,
      :address_line2,
      :city,
      :state,
      :postal_code,
      :country,
      :lat,
      :lng,
      :nightly_price,
      :cleaning_fee
    )
  end

  def listing_update_params
    params.require(:listing).permit(
      :title,
      :about,
      :max_guests,
      :status,
      :nightly_price,
      :cleaning_fee
    )
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @listings = Listing.published
  end

  def show
    @listing = Listing.published.find(params[:id])
  end
end

app/helpers/host/listings_helper.rb
module Host::ListingsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/listings/index.html.erb
<h1>Listings</h1>

<ul>

  <% if @listings.any? %>
    <% @listings.each do |listing| %>
      <li>
        <%= link_to listing.title, listing_path(listing) %>
      </li>
    <% end %>
  <% else %>
    <li>There are currently no listings available</li>
  <% end %>

</ul>

app/views/listings/show.html.erb
<span class="text-sm italic text-gray-300 -pt-10">
  <%= mail_to @listing.host.email, @listing.host.name %>
</span>
<h1>Listings for <%= @listing.title %> </h1>
<div class="flex justify-center">
  <div class="relative w-3/4 mt-10 overflow-hidden text-black shadow-lg rounded-xl">
    <div class="w-auto p-10 bg-yellow-100">
      <p>
        <strong>Title:</strong> <%= @listing.title %>
      </p>
      <p>
        <%= form_with url: reservations_path do |form| %>
          <input type="hidden" name="reservation[listing_id]" value="<%= @listing.id %>">
          <%#= form.hidden_field "reservation[listing_id]", value: @listing_id %>
          <%= form.submit "Reserve 2" %>
        <% end %>
      </p>
      <p>
        <strong>Price per night:</strong><%= number_to_currency( @listing.nightly_price / 100, precision: 0 ) %>
      </p>

      <p>
        <strong>Cleaning fees:</strong><%= number_to_currency( @listing.cleaning_fee/100, precision: 0 ) %>
      </p>

      <p>
        <strong>About:</strong> <%= @listing.about %>
      </p>

      <p>
        <strong>Max guests allowed:</strong> <%= @listing.max_guests %>
      </p>

      <p>
        <strong>Location:</strong> <%= address(@listing) %>
      </p>
      <div class="mt-5 photo_lists">
        <% if @listing.photos.exists? %>
          <% @listing.photos.each do |photo| %>
            <%= image_tag photo.image_url %>
          <% end %>
        <% end %>
      </div>
    </div>
  </div>