config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  resources :listings, only: [:index, :show]
  resources :reservations do
    member do
      post '/cancel' => 'reservations#cancel'
    end
  end
  post 'webhooks/:source' => 'webhooks#create'

  namespace :host do
    resources :merchant_settings do
      collection do
        get '/connect' => 'merchant_settings#connect'
        get '/connected' => 'merchant_settings#connected'
      end
    end
    resources :listings do 
      resources :photos, only: [ :index, :new, :create, :destroy ]
      resources :rooms, only: [:index, :create, :destroy]
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/models/listing.rb
# == Schema Information
#
# Table name: listings
#
#  id                :integer          not null, primary key
#  host_id           :integer          not null
#  title             :string           not null
#  about             :text
#  max_guests        :integer          default("1")
#  address_line1     :string
#  address_line2     :string
#  city              :string
#  state             :string
#  postal_code       :string
#  country           :string
#  lat               :decimal(10, 6)
#  lng               :decimal(10, 6)
#  status            :integer          default("0")
#  created_at        :datetime         not null
#  updated_at        :datetime         not null
#  nightly_price     :integer
#  cleaning_fee      :integer
#  stripe_product_id :string
#
# Indexes
#
#  index_listings_on_host_id  (host_id)
#

class Listing < ApplicationRecord
  validates :title, presence: true
  validates :max_guests, numericality: { greater_than: 0, less_than_or_equel_to: 100 }
  validates :nightly_price, numericality: { greater_than: 0 }
  validates :cleaning_fee, numericality: { greater_than: 0 }
  belongs_to :host, class_name: 'User'
  has_many :rooms
  has_many :photos

  enum status: { draft: 0, published: 1, archived: 2 }

  scope :published, -> { where(status: :published )}


  after_commit :maybe_create_stripe_product, on: [:create, :update]

  def maybe_create_stripe_product
    return if !stripe_product_id.blank?

    product = Stripe::Product.create(
      name: title,
      url: Rails.application.routes.url_helpers.url_for(self),
      metadata: {
        clearbnb_id: id,
      }
    )
    self.update(stripe_product_id: product.id)
  end



end

app/controllers/host/listings_controller.rb
class Host::ListingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @listings = current_user.listings.all
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_create_params)
    if @listing.save
      redirect_to host_listing_path(@listing)
    else
      flash.now[:errors] = @listing.errors.full_messages
      render :new
    end
  end

  def show
    @listing = current_user.listings.find(params[:id])
  end

  def edit
    @listing = current_user.listings.find(params[:id])
  end

  def update
    @listing = current_user.listings.find(params[:id])
    if @listing.update(listing_update_params)
      redirect_to host_listing_path(@listing)
    else
      flash.now[:errors] = @listing.errors.full_messages
      render :edit
    end
  end


  def destroy
    @listing = current_user.listings.find(params[:id])
    @listing.update(status: :archived)
    redirect_to host_listing_path
  end

  private

  def listing_create_params
    params.require(:listing).permit(
      :title,
      :about,
      :max_guests,
      :address_line1,
      :address_line2,
      :city,
      :state,
      :postal_code,
      :country,
      :lat,
      :lng,
      :nightly_price,
      :cleaning_fee
    )
  end

  def listing_update_params
    params.require(:listing).permit(
      :title,
      :about,
      :max_guests,
      :status,
      :nightly_price,
      :cleaning_fee
    )
  end
end

app/controllers/host/merchant_settings_controller.rb
class Host::MerchantSettingsController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def connect
    if !current_user.stripe_account_id.present?
      account = Stripe::Account.create(
        type: 'express',
        country: 'US',
        email: current_user.email,
        capabilities: {
          card_payments: {requested: true},
          transfers: {requested: true},
          tax_reporting_us_1099_k: {requested: true},
        },
        business_type: 'individual',
        individual: {
          email: current_user.email,
        }
      )
      current_user.update(
        is_host: true,
        stripe_account_id: account.id
      )
      # redirect_to host_merchant_settings_path
      link = Stripe::AccountLink.create(
        account: current_user.stripe_account_id,
        refresh_url: connect_host_merchant_settings_url,
        return_url: connected_host_merchant_settings_url,
        type: 'account_onboarding',
      )
      redirect_to link.url, status: :see_other, allow_other_hosts: true
      return
    end
    redirect_to host_merchant_settings_path
  end

  def connected
    render text: 'Connected'
  end

end

app/controllers/host/photos_controller.rb
class Host::PhotosController < ApplicationController
  before_action :authenticate_user!

  def index
    @listing = current_user.listings.find(params[:listing_id])
    @photo = @listing.photos
  end

  def new
    @photo = Photo.new
  end

  def create
    @listing = current_user.listings.find(params[:listing_id])
    @photo = @listing.photos.build(photo_params)
    if @photo.save
      redirect_to host_listing_photos_path(@listing)
    else
      flash[:errors] = @photo.errors.full_messages
    end
  end

  def destroy
    @photo = @photo.find(params[:id])
    @photo.destroy
    render json: {}
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :image)
  end
end

app/controllers/host/rooms_controller.rb
class Host::RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @listing = current_user.listings.find(params[:listing_id])
    @rooms = @listing.rooms.all
  end

  def create
    @listing = current_user.listings.find(params[:listing_id])
    @room = @listing.rooms.new(room_params)
    if !@room.save
      flash[:errors] = @room.errors.full_messages
    end
    redirect_to host_listing_rooms_path(@listing)
  end

  def destroy
    @listing = current_user.listings.find(params[:listing_id])
    @room = @listing.rooms.find(params[:id])

    @room.destroy

    redirect_to host_listing_rooms_path(@listing)

  end

  private

  def room_params
    params.require(:room).permit(:room_type, beds_attributes: [:bed_size])
  end
end

app/controllers/listings_controller.rb
class ListingsController < ApplicationController
  def index
    @listings = Listing.published
  end

  def show
    @listing = Listing.published.find(params[:id])
  end
end

app/helpers/host/listings_helper.rb
module Host::ListingsHelper
end

app/helpers/host/merchant_settings_helper.rb
module Host::MerchantSettingsHelper
end

app/helpers/host/photos_helper.rb
module Host::PhotosHelper
end

app/helpers/host/rooms_helper.rb
module Host::RoomsHelper
end

app/helpers/listings_helper.rb
module ListingsHelper
end

app/views/host/listings/edit.html.erb
<h1 class="mb-4 text-2xl font-bold">Edit <%= @listing.title %></h1>

<%= render partial: "shared/errors" %>

<form action="<%= host_listing_path(@listing) %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <input type="hidden" name="_method" value="PUT">

  <p>
    <label for="title">Title</label>
    <input type="text" name="listing[title]" id="title" value="<%= @listing.title %>">
  </p>

  <p>
    <label for="about">About</label>
    <textarea id="about" name="listing[about]"><%= @listing.about %></textarea>
  </p>

  <p>
    <label for="max_guests">How many people maxium can stay?</label>
    <input type="number" id="max_guests" name="listing[max_guests]" value="<%= @listing.max_guests %>" min="1" max="100" step="1">
  </p>


  <p>
    <label for="nightly_price">Nightly Price</label>
    <input type="number" id="nightly_price" name="listing[nightly_price]" value="<%= @listing.nightly_price %>" min="1" step="1">
  </p>

  <p>
    <label for="cleaning_fee">Cleaning Fee</label>
    <input type="number" id="cleaning_fee" name="listing[cleaning_fee]" value="<%= @listing.cleaning_fee %>" min="1" step="1">
  </p>

  <p>
    <label for="status">Status</label>
    <select name="listing[status]">
      <% Listing.statuses.keys.each do |status| %>
        <option <%= 'selected' if @listing.status == status %>><%= status %></option>
      <% end %>
    </select>
  </p>

  <p>
    <input type="submit" value="Update listing" class="btn btn-primary">
  </p>
</form>

app/views/host/listings/index.html.erb
<h1 class="mb-4 text-2xl font-bold">Your listings</h1>

<a href="/host/listings/new" class="px-4 py-2 font-bold text-white bg-blue-500 rounded-full hover:bg-blue-700">
  Add a new listing
</a>

<!-- This example requires Tailwind CSS v2.0+ -->
<div class="mt-8 overflow-hidden bg-white shadow sm:rounded-md">
  <ul role="list" class="divide-y divide-gray-200">
    <% @listings.each do |l| %>
    <li>
      <a href="<%= host_listing_path(l) %>" class="block hover:bg-gray-50">
        <div class="flex items-center px-4 py-4 sm:px-6">
          <div class="flex items-center flex-1 min-w-0">
            <div class="flex-shrink-0">
            <% if l.photos.any? %>
            <img class="w-12 h-12 rounded-full" src="<%= l.photos.first.image_url if l.photos.any? %>" alt="">
          <% else %>
<img class="w-12 h-12 rounded-full" src="https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=facearea&facepad=2&w=256&h=256&q=80" alt="">
          <% end %>
            </div>
            <div class="flex-1 min-w-0 px-4 md:grid md:grid-cols-2 md:gap-4">
              <div>
                <p class="text-sm font-medium text-indigo-600 truncate"><%= l.title %></p>
                <p class="flex items-center mt-2 text-sm text-gray-500">
                  <!-- Heroicon name: solid/mail -->
                  <svg xmlns="http://www.w3.org/2000/svg" class="w-5 h-5" viewBox="0 0 20 20" fill="currentColor">
                    <path fill-rule="evenodd" d="M5.05 4.05a7 7 0 119.9 9.9L10 18.9l-4.95-4.95a7 7 0 010-9.9zM10 11a2 2 0 100-4 2 2 0 000 4z" clip-rule="evenodd" />
                  </svg>
                  <span class="truncate"><%= address(l) %></span>
                </p>
              </div>
              <div class="hidden md:block">
                <div>
                  <!-- <p class="text-sm text-gray-900"> -->
                  <!--   Last seen -->
                  <!--   <time datetime="2020-01-07">January 7, 2020</time> -->
                  <!-- </p> -->
                  <p class="flex items-center mt-2 text-sm text-gray-500">
                    <!-- Heroicon name: solid/check-circle -->
                    <% if l.published? %>
                    <svg class="flex-shrink-0 mr-1.5 h-5 w-5 text-green-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
                      <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm3.707-9.293a1 1 0 00-1.414-1.414L9 10.586 7.707 9.293a1 1 0 00-1.414 1.414l2 2a1 1 0 001.414 0l4-4z" clip-rule="evenodd" />
                    </svg>
                    <% else %>
                    <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5 flex-shrink-0 mr-1.5 text-yellow-400" viewBox="0 0 20 20" fill="currentColor">
                      <path fill-rule="evenodd" d="M10 18a8 8 0 100-16 8 8 0 000 16zm1-12a1 1 0 10-2 0v4a1 1 0 00.293.707l2.828 2.829a1 1 0 101.415-1.415L11 9.586V6z" clip-rule="evenodd" />
                    </svg>
                    <% end %>
                    <%= l.status.capitalize %>
                  </p>
                </div>
              </div>
            </div>
          </div>
          <div>
            <!-- Heroicon name: solid/chevron-right -->
            <svg class="w-5 h-5 text-gray-400" xmlns="http://www.w3.org/2000/svg" viewBox="0 0 20 20" fill="currentColor" aria-hidden="true">
              <path fill-rule="evenodd" d="M7.293 14.707a1 1 0 010-1.414L10.586 10 7.293 6.707a1 1 0 011.414-1.414l4 4a1 1 0 010 1.414l-4 4a1 1 0 01-1.414 0z" clip-rule="evenodd" />
            </svg>
          </div>
        </div>
      </a>
    </li>
    <% end %>
  </ul>
</div>


  <!-- <#%= button_to "delete", host_listing_path(l), method: :delete %> -->

app/views/host/listings/new.html.erb
<h1>List your property</h1>

<% if flash[:errors] %>
  <% flash[:errors].each do |error| %>
    <p>
      <%= error %>
    </p>
  <% end %>

<% end %>


<form action="/host/listings" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="title">Title<br>
    <input type="text" name="listing[title]" id="title" value="<%= @listing.title %>">
  </label><br>
  <label for="about">About</label><br>
  <input type="text" name="listing[about]" id="about" value="<%= @listing.about %>">
  </label><br>
  <label for="max_guests">Maximum guest<br>
    <input type="number" name="listing[max_guests]" id="max_guests" value="<%= @listing.max_guests %>" min="1" max="100" steps="1">
  </label><br>

  <p>
    <label for="nightly_price">How much?</label>
    <input type="number" id="nightly_price" name="listing[nightly_price]" value="<%= @listing.nightly_price %>" min="1" step="1">
  </p>

  <p>
    <label for="cleaning_fee">Cleaning Fee</label>
    <input type="number" id="cleaning_fee" name="listing[cleaning_fee]" value="<%= @listing.cleaning_fee %>" min="1" step="1">
  </p>

  <div data-controller="address" data-action="map-loaded@window->address#initGoogle">
    <label for="address">Address<br> </label>
    <input type="text" id="address" data-address-target="input" autocomplete="off">
    <input type="hidden" name="listing[address_line1]" data-address-target="line1"> 
    <input type="hidden" name="listing[address_line2]" data-address-target="line2"> 
    <input type="hidden" name="listing[city]" data-address-target="city">
    <input type="hidden" name="listing[state]" data-address-target="state">
    <input type="hidden" name="listing[postal_code]" data-address-target="postal_code">
    <input type="hidden" name="listing[country]" data-address-target="country">
    <input type="hidden" name="listing[lat]" data-address-target="lat">
    <input type="hidden" name="listing[lng]" data-address-target="lng">
  </div>
  </div>
  <br>
  <p>
    <input type="submit" value="Submit">
  </p>
</form>

app/views/host/listings/show.html.erb
<h1><%= @listing.title %></h1>

<%= link_to "Edit Details", edit_host_listing_path(@listing) %>
<%= link_to "Edit Rooms", host_listing_rooms_path(@listing) %>
<%= link_to "Edit Photos", host_listing_photos_path(@listing) %>
<pre>
<%= JSON.pretty_generate(@listing.as_json) %>
</pre>


<div class="my-2 border-t-2">

  <p>
    <%= @listing.title %>
  </p>
  <p>
    <%= @listing.about %>
  </p>
  <p>
    <%= @listing.max_guests %>
  </p>
  <div class="photo_lists">
    <% if @listing.photos.exists? %>
      <% @listing.photos.each do |photo| %>
        <%= image_tag photo.image_url %>
      <% end %>
    <% end %>
  </div>
</div>