config/routes.rb
Rails.application.routes.draw do
  root to: 'static_pages#home'

  resources :listings, only: [:index, :show]
  resources :reservations do
    member do
      post '/cancel' => 'reservations#cancel'
    end
  end
  post 'webhooks/:source' => 'webhooks#create'

  namespace :host do
    resources :merchant_settings do
      collection do
        get '/connect' => 'merchant_settings#connect'
        get '/connected' => 'merchant_settings#connected'
      end
    end
    resources :listings do 
      resources :photos, only: [ :index, :new, :create, :destroy ]
      resources :rooms, only: [:index, :create, :destroy]
    end
  end

  devise_for :users, controllers: { omniauth_callbacks: 'users/omniauth_callbacks' }

end

app/models/room.rb
# == Schema Information
#
# Table name: rooms
#
#  id         :integer          not null, primary key
#  listing_id :integer          not null
#  room_type  :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#
# Indexes
#
#  index_rooms_on_listing_id  (listing_id)
#

class Room < ApplicationRecord
  belongs_to :listing
  has_many :beds, dependent: :destroy
  accepts_nested_attributes_for :beds

  enum room_type: {
    bedroom: 0,
    primary_bedroom: 1,
    living_room: 2,
    basement: 3
  }
end

app/controllers/host/listings_controller.rb
class Host::ListingsController < ApplicationController
  before_action :authenticate_user!

  def index
    @listings = current_user.listings.all
  end

  def new
    @listing = Listing.new
  end

  def create
    @listing = current_user.listings.new(listing_create_params)
    if @listing.save
      redirect_to host_listing_path(@listing)
    else
      flash.now[:errors] = @listing.errors.full_messages
      render :new
    end
  end

  def show
    @listing = current_user.listings.find(params[:id])
  end

  def edit
    @listing = current_user.listings.find(params[:id])
  end

  def update
    @listing = current_user.listings.find(params[:id])
    if @listing.update(listing_update_params)
      redirect_to host_listing_path(@listing)
    else
      flash.now[:errors] = @listing.errors.full_messages
      render :edit
    end
  end


  def destroy
    @listing = current_user.listings.find(params[:id])
    @listing.update(status: :archived)
    redirect_to host_listing_path
  end

  private

  def listing_create_params
    params.require(:listing).permit(
      :title,
      :about,
      :max_guests,
      :address_line1,
      :address_line2,
      :city,
      :state,
      :postal_code,
      :country,
      :lat,
      :lng,
      :nightly_price,
      :cleaning_fee
    )
  end

  def listing_update_params
    params.require(:listing).permit(
      :title,
      :about,
      :max_guests,
      :status,
      :nightly_price,
      :cleaning_fee
    )
  end
end

app/controllers/host/merchant_settings_controller.rb
class Host::MerchantSettingsController < ApplicationController
  before_action :authenticate_user!
  def index
  end

  def connect
    if !current_user.stripe_account_id.present?
      account = Stripe::Account.create(
        type: 'express',
        country: 'US',
        email: current_user.email,
        capabilities: {
          card_payments: {requested: true},
          transfers: {requested: true},
          tax_reporting_us_1099_k: {requested: true},
        },
        business_type: 'individual',
        individual: {
          email: current_user.email,
        }
      )
      current_user.update(
        is_host: true,
        stripe_account_id: account.id
      )
      # redirect_to host_merchant_settings_path
      link = Stripe::AccountLink.create(
        account: current_user.stripe_account_id,
        refresh_url: connect_host_merchant_settings_url,
        return_url: connected_host_merchant_settings_url,
        type: 'account_onboarding',
      )
      redirect_to link.url, status: :see_other, allow_other_hosts: true
      return
    end
    redirect_to host_merchant_settings_path
  end

  def connected
    render text: 'Connected'
  end

end

app/controllers/host/photos_controller.rb
class Host::PhotosController < ApplicationController
  before_action :authenticate_user!

  def index
    @listing = current_user.listings.find(params[:listing_id])
    @photo = @listing.photos
  end

  def new
    @photo = Photo.new
  end

  def create
    @listing = current_user.listings.find(params[:listing_id])
    @photo = @listing.photos.build(photo_params)
    if @photo.save
      redirect_to host_listing_photos_path(@listing)
    else
      flash[:errors] = @photo.errors.full_messages
    end
  end

  def destroy
    @photo = @photo.find(params[:id])
    @photo.destroy
    render json: {}
  end

  private

  def photo_params
    params.require(:photo).permit(:caption, :image)
  end
end

app/controllers/host/rooms_controller.rb
class Host::RoomsController < ApplicationController
  before_action :authenticate_user!

  def index
    @listing = current_user.listings.find(params[:listing_id])
    @rooms = @listing.rooms.all
  end

  def create
    @listing = current_user.listings.find(params[:listing_id])
    @room = @listing.rooms.new(room_params)
    if !@room.save
      flash[:errors] = @room.errors.full_messages
    end
    redirect_to host_listing_rooms_path(@listing)
  end

  def destroy
    @listing = current_user.listings.find(params[:listing_id])
    @room = @listing.rooms.find(params[:id])

    @room.destroy

    redirect_to host_listing_rooms_path(@listing)

  end

  private

  def room_params
    params.require(:room).permit(:room_type, beds_attributes: [:bed_size])
  end
end

app/helpers/host/listings_helper.rb
module Host::ListingsHelper
end

app/helpers/host/merchant_settings_helper.rb
module Host::MerchantSettingsHelper
end

app/helpers/host/photos_helper.rb
module Host::PhotosHelper
end

app/helpers/host/rooms_helper.rb
module Host::RoomsHelper
end

app/views/host/rooms/_form.html.erb
<div data-controller="room">

  <template data-room-target="bedFields">
    <label for="room_type" class="block text-sm font-medium text-gray-700">Bed Size</label>
    <select id="room_type" name="room[beds_attributes][][bed_size]" class="block w-full py-2 pl-3 pr-10 mt-1 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md">
      <% Bed.bed_sizes.each do |bed_size, _| %> 
        <option> <%= bed_size %> </option>
      <% end %>
    </select>
  </template>


  <form action="<%= host_listing_rooms_path(listing) %>" method="post">
    <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
    <label for="room_type" class="block text-sm font-medium text-gray-700">Room type</label>
    <select id="room_type" name="room[room_type]" class="block w-full py-2 pl-3 pr-10 mt-1 text-base border-gray-300 focus:outline-none focus:ring-indigo-500 focus:border-indigo-500 sm:text-sm rounded-md">
      <% Room.room_types.each do |rt, _| %> 
        <option> <%= rt %> </option>
      <% end %>
    </select>

<fieldset data-room-target="beds">
  <legend>Beds</legend>
  
</fieldset>

    <p>
      <a href="#" data-action="room#addBed">Add a Bed</a>
    </p>

    <input type="submit" value="Add Room">
  </form>
</div>

app/views/host/rooms/index.html.erb
<h1 class="mb-4 text-2xl font-bold">Rooms</h1>

<%= link_to "Back to #{@listing.title}", host_listing_path(@listing) %>

<ul role="list" class="grid grid-cols-1 gap-6 sm:grid-cols-2 lg:grid-cols-3">
  <% @rooms.each do |room| %>
    <li class="bg-white rounded-lg shadow col-span-1 divide-y divide-gray-200">
      <div class="flex items-center justify-between w-full p-6 space-x-6">
        <div class="flex-1 truncate">
          <div class="flex items-center space-x-3">
            <h3 class="text-sm font-medium text-gray-900 truncate"><%= room.room_type %></h3>
            <span class="flex-shrink-0 inline-block px-2 py-0.5 text-green-800 text-xs font-medium bg-green-100 rounded-full">
              <%= room.beds.count %>
            </span>
          </div>
          <% room.beds.each do |bed| %>
            <p class="mt-1 text-sm text-gray-500 truncate"><%= bed.bed_size %></p>
          <% end %>
          <%= button_to "Delete", host_listing_room_path(@listing, room), method: :delete %>
        </div>
      </div>
    </li>
  <% end %>
</ul>

<%= render partial: 'form', locals: { listing: @listing } %>